# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'


  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
